name: Export Docker Image

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Pull and Save Image
        run: |
          docker pull ghcr.io/byjoey/yx-tools:main-c2b837d
          docker save ghcr.io/byjoey/yx-tools:main-c2b837d | gzip > yx-tools.tar.gz
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: yx-tools-image
          path: yx-tools.tar.gz
